CREATE DATABASE IF NOT EXISTS AnimalStoreDb;
USE AnimalStoreDb;

-- Animals tables

CREATE TABLE IF NOT EXISTS cat(
	Id INT AUTO_INCREMENT NOT NULL,
	Type VARCHAR(32) NOT NULL,
	Name VARCHAR(32) NOT NULL,
	Age INT UNSIGNED NOT NULL,
	Price DOUBLE UNSIGNED NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS dog(
	Id INT AUTO_INCREMENT NOT NULL,
	Type VARCHAR(32) NOT NULL,
	Name VARCHAR(32) NOT NULL,
	Age INT UNSIGNED NOT NULL,
	Price DOUBLE UNSIGNED NOT NULL,
	Breed VARCHAR(32),
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS fox(
	Id INT AUTO_INCREMENT NOT NULL,
	Type VARCHAR(32) NOT NULL,
	Name VARCHAR(32) NOT NULL,
	Age INT UNSIGNED NOT NULL,
	Price DOUBLE UNSIGNED NOT NULL,
	PRIMARY KEY(Id)
);

-- Main table

CREATE TABLE IF NOT EXISTS Id_Animal(
	Id INT AUTO_INCREMENT NOT NULL,
	Type VARCHAR(32) NOT NULL,
	AnimalId INT NOT NULL,
	PRIMARY KEY(Id)
);

GRANT ALL ON AnimalStoreDb.* TO AnimalStoreAdmin@'#' IDENTIFIED BY 'secret';
