CREATE DATABASE IF NOT EXISTS AnimalStoreDb;
USE AnimalStoreDb;

-- Animals tables

CREATE TABLE IF NOT EXISTS Cat(
	Id INT AUTO_INCREMENT NOT NULL,
	Type VARCHAR(32) NOT NULL,
	Name VARCHAR(32) NOT NULL,
	Age UNSIGNED INT NOT NULL,
	Price USIGNED DOUBLE NOT NULL
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS Dog(
	Id INT AUTO_INCREMENT NOT NULL,
	Type VARCHAR(32) NOT NULL,
	Name VARCHAR(32) NOT NULL,
	Age UNSIGNED INT NOT NULL,
	Price USIGNED DOUBLE NOT NULL,
	Breed VARCHAR(32) NOT NULL,
	PRIMARY KEY(Id)
);

CREATE TABLE IF NOT EXISTS Fox(
	Id INT AUTO_INCREMENT NOT NULL,
	Type VARCHAR(32) NOT NULL,
	Name VARCHAR(32) NOT NULL,
	Age UNSIGNED INT NOT NULL,
	Price USIGNED DOUBLE NOT NULL,
	PRIMARY KEY(Id)
);

-- Main table

CREATE TABLE IF NOT EXISTS Id_Animal(
	Id INT AUTO_INCREMENT NOT NULL,
	Type VARCHAR(32) NOT NULL,
	AnimalId INT NOT NULL,
	PRIMARY KEY(Id)
);

GRANT ALL ON AnimalStoreDb.* TO AnimalStoreAdmin@localhost IDENTIFIED BY 'secret';
