version: '3'
services:
  animal_store:
      build:
        context: ./..
        dockerfile: './Лаб. 3/Dockerfile'
      ports:
        - 2525:2525
      volumes:
        - "./app/log/:/app/log"
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: on-failure
    command: --init-file /data/application/init.sql
    environment:
        - MYSQL_DATABASE=AnimalStoreDb
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=AnimalStoreAdmin
        - MYSQL_PASSWORD=secret
    ports:
        - "33060:3306"
    volumes:
        # - "./database/data/mysql:/var/lib/mysql"
        - "./database/init.sql:/data/application/init.sql"